host: 127.0.0.1

server:
  port: 8080
spring:
  application:
    name: claude_Speicher
  datasource:
    url: jdbc:mysql://${host}/Cloud_Speicher?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "0317"

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true

mein:
  val:
    file:
      path: "../files"
      publicPath: "../files/public"

    signKey: "reisen"
    expire: 30 #Tage
    url: ${host}